VIA-175 AS Modify upload step in build stage

diff --git a/.github/workflows/stage-3-build.yaml b/.github/workflows/stage-3-build.yaml
--- a/.github/workflows/stage-3-build.yaml
+++ b/.github/workflows/stage-3-build.yaml
@@ -81,15 +81,20 @@ jobs:
           aws-region: ${{ env.AWS_REGION }}
       - name: "Upload Packages To S3"
         run: |
-          aws s3api put-object --bucket "${AWS_S3_ARTEFACTS_BUCKET}" --key "sha/${RELEASE_VERSION}/open-next.zip" --body "open-next.zip" --if-none-match '*'
-          EXIT=$?
-
-          if [ $EXIT -ne 0 ]; then
-            echo "Uploading artifacts to S3 bucket failed!"
-            echo "command exited with $EXIT"
+#          Prevent overwriting of existing artefacts
+          aws s3api put-object --bucket "${AWS_S3_ARTEFACTS_BUCKET}" --key "sha/${RELEASE_VERSION}/open-next.zip" --body "open-next.zip" --if-none-match '*' || {
+            echo "Uploading open-next.zip to S3 bucket failed!"
             exit 1
-          else
-            aws s3api put-object --bucket "${AWS_S3_ARTEFACTS_BUCKET}" --key "sha/${RELEASE_VERSION}/lambda.zip" --body "lambda.zip" --if-none-match '*'
-            aws s3api put-object --bucket "${AWS_S3_ARTEFACTS_BUCKET}" --key "sha/${RELEASE_VERSION}/workflow.log" --body "workflow.log" --if-none-match '*'
-            echo "Upload artifacts to S3 bucket succeeded!"
-          fi
+          }
+
+          aws s3api put-object --bucket "${AWS_S3_ARTEFACTS_BUCKET}" --key "sha/${RELEASE_VERSION}/lambda.zip" --body "lambda.zip" --if-none-match '*' || {
+            echo "Uploading lambda.zip to S3 bucket failed!"
+            exit 1
+          }
+
+          aws s3api put-object --bucket "${AWS_S3_ARTEFACTS_BUCKET}" --key "sha/${RELEASE_VERSION}/workflow.log" --body "workflow.log" --if-none-match '*' || {
+            echo "Uploading workflow.log to S3 bucket failed!"
+            exit 1
+          }
+
+          echo "Upload artifacts to S3 bucket succeeded!"
